export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGIN_LOGOUT'

export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCCESS'
export const ADMIN_DETAILS_FAIL = 'ADMIN_REGISTER_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const ADMIN_DETAILS_RESET = 'ADMIN_REGISTER_RESET'


export const ADMIN_UPDATE_PROFILE_REQUEST = 'ADMIN_UPDATE_PROFILE_REQUEST'
export const ADMIN_UPDATE_PROFILE_SUCCESS = 'ADMIN_UPDATEPROFILE__SUCCCESS'
export const ADMIN_UPDATE_PROFILE_FAIL = 'ADMIN_UPDATE_PROFILE__FAIL'
export const ADMIN_LIST_RESET = 'ADMIN_LIST_RESET'