export const MOVIE_REGISTER_FAIL = 'MOVIE_REGISTER_FAIL'
export const MOVIE_REGISTER_REQUEST = 'MOVIE_REGISTER_REQUEST'
export const MOVIE_REGISTER_SUCCESS = 'MOVIE_REGISTER_SUCCESS'

export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'
export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'