export const RENT_CREATE_REQUEST = 'RENT_CREATE_REQUEST'
export const RENT_CREATE_SUCCESS = 'RENT_CREATE_SUCCESS'
export const RENT_CREATE_FAIL = 'RENT_CREATE_FAIL'

export const RENT_LIST_REQUEST = 'RENT_LIST_REQUEST'
export const RENT_LIST_SUCCESS = 'RENT_LIST_SUCCESS'
export const RENT_LIST_FAIL = 'RENT_LIST_FAIL'